/** @type {import('tailwindcss').Config} */
module.exports = {
  theme: {
    extend: {
      typography: () => ({
        nord: {
          css: {
            "--tw-prose-body": "var(--color-nord0)",
            "--tw-prose-headings": "var(--color-nord7)",
            "--tw-prose-lead": "var(--color-nord0)",
            "--tw-prose-links": "var(--color-nord7)",
            "--tw-prose-bold": "var(--color-nord0)",
            "--tw-prose-counters": "var(--color-gold)",
            "--tw-prose-bullets": "var(--color-gold)",
            "--tw-prose-hr": "var(--color-gold)",
            "--tw-prose-quotes": "var(--color-nord3)",
            "--tw-prose-quote-borders": "var(--color-gold)",
            "--tw-prose-captions": "var(--color-nord2)",
            "--tw-prose-code": "var(--color-nord1)",
            "--tw-prose-pre-code": "var(--color-nord1)",
            "--tw-prose-pre-bg": "var(--color-nord4)",
            "--tw-prose-th-borders": "var(--color-gold)",
            "--tw-prose-td-borders": "var(--color-gold)",
            "--tw-prose-invert-body": "var(--color-nord6)",
            "--tw-prose-invert-headings": "var(--color-nord7)",
            "--tw-prose-invert-lead": "var(--color-nord6)",
            "--tw-prose-invert-links": "var(--color-nord7)",
            "--tw-prose-invert-bold": "var(--color-nord6)",
            "--tw-prose-invert-counters": "var(--color-gold)",
            "--tw-prose-invert-bullets": "var(--color-gold)",
            "--tw-prose-invert-hr": "var(--color-gold)",
            "--tw-prose-invert-quotes": "var(--color-nord4)",
            "--tw-prose-invert-quote-borders": "var(--color-nord4)",
            "--tw-prose-invert-captions": "var(--color-nord5)",
            "--tw-prose-invert-code": "var(--color-nord5)",
            "--tw-prose-invert-pre-code": "var(--color-nord5)",
            "--tw-prose-invert-pre-bg": "var(--color-nord2)",
            "--tw-prose-invert-th-borders": "var(--color-gold)",
            "--tw-prose-invert-td-borders": "var(--color-gold)",
          },
        },
      }),
    },
  },
};
